### ISSUE TITLE
部費の導入を考えています。

### ISSUE THREAD

**Issue by Tatmius** [HUITGroup/agenda#5]
## 概要
現在HUITは参加費等を徴収していませんが、部費の導入を考えています。
想定している金額は半期で1200円ほど。

## なぜ？
主な目的は2つ、モチベーションのためとサーバー等の固定費に当てるためです。

### モチベーション
お金を取ることで、「お金を払ってるからちゃんと参加するか」という気持ちになってもらうためです。
余ったお金をどうするかは未定ですが、年度末に清算するようにしたいと思っています(出来るだけ繰り越しはしたくない)

### 固定費として
これまでもHUITではサーバー代金をどうするかという話題が出ていました。サーバー代等をまかなうことが出来ればより活動に自由度が増し幅も広がるかと思います。例えばHPを作ったり、サークルで使うチャットツールを作れたりするといいかもしれません。

## TODO
- [ ] ドキュメントにまとめる（最低限引継ぎできる状態に持っていく）

**Comment by manattan** [comment]
（対面でいけるなら）イベントの設備代や場所代、お菓子代、打ち上げ代とか。
サークル内でラズパイや3Dプリンターを持っているだけでもいろんなアプローチができそうですね。
