### ISSUE TITLE
ハッカソンなどの資料をどこに保存するかを決める

### ISSUE THREAD

**Issue by shoumoji** [HUITGroup/agenda#8]
### WHAT

有用だが1度きりの、サークル外に公開しない資料を一括でどこに置くかきめたい。(ハッカソンの資料等)  
出来れば見つけやすく、読みやすい場所が良い。  

### WHY

isuconの振り返り資料など、有用だが1度きりの資料を、今後のサークルの人が見やすい形で保存したい。

**Comment by shoumoji** [comment]
### 選択肢
- github (hackmdと連携可、永続性あり)
- esa (サークル内の情報を一括管理できる)
- hackmd(グループ作れる)

**Comment by Tatmius** [comment]
過去のLT会の資料なんかはPDFやったりpptxやったりするのでLT会終わりにgoogle driveに入れてもらうみたいな運用してるんですが、アクセシビリティが低いので、Markdownの文章以外も一緒に考えれたらと思います。

Discordは月額課金ユーザーでないと投稿出来るファイルサイズに限界があるので、
たとえば、サークルのgoogle アカウントで各種共有フォルダを作ってそれのリンクをDiscordに貼るみたいな運用もアリなのかなと思います。(もし15GBで足りなくなったら部費でgoogle driveに課金とかしてもいいので)

**Comment by shoumoji** [comment]
discordのlinksチャンネルにurlとして書いておく
